### ISSUE TITLE
Controls should be read-only

### ISSUE THREAD

**Issue by lindsayking** [Esri/damage-assessment-summary#18]
The Summary Report currently gives the impression that values can be edited, because it appears that  values can be changed on the widget panel:
![image](https://cloud.githubusercontent.com/assets/4316336/15370980/3931823e-1cee-11e6-9e32-13b9761285fb.png)

These controls should be read-only so that users aren't tempted to change values or confused by the impression that it is possible to do so.

**Comment by jmhauck** [comment]
Being able to make temp edits to the values for the duration of the session was supported in the previous WPF release. It should work here now as well. There was an issue with pulling the local updates for non-Note fields that is handled in the commit referenced above.
